FAQ/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'FAQ'

urlpatterns = [
	url(r'^$', cache_page(60*15)(views.FaqListView.as_view()), name='faq_list'),
]

blog/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'blog'

urlpatterns = [

    url(r'^$', cache_page(60*15)(views.BlogListView.as_view()), name='blog_list'),

    url(r'^(?P<blog_slug>[\w-]+)/$',
        views.blog_details_view, name='blogdetail'),

    url(r'^category/(?P<blog_category_slug>[\w-]+)/$',
        views.blog_categories_details, name='blog_category_details'),

    url(r'^tag/(?P<blog_tag_slug>[\w-]+)/$',
        views.blog_tag_details, name='blog_tag_details'),

    url(r'^search/item/$',
        views.search, name='search_blog'),
]

blog/models.py
from PIL import Image
import sys
import os
from io import BytesIO

from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.files.uploadedfile import InMemoryUploadedFile
# Create your models here.


class BlogTags(models.Model):
    """
    Blog Tags Model
    """
    name = models.CharField(max_length=200)
    slug = models.SlugField(
        max_length=200, unique=True, null=True, blank=True)

    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(BlogTags, self).save(*args, **kwargs)


class BlogCategories(models.Model):
    """
    Blog Categories
    """
    title = models.CharField(max_length=40, default='Uncategorized')
    slug = models.SlugField(
        max_length=200, unique=True, null=True, blank=True)

    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Returns absolute url for a blog categories
        """
        return reverse("blog:blog_category_details", kwargs={'blog_category_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogCategories, self).save(*args, **kwargs)


class Blog(models.Model):
    """
    Blog Model
    """
    date = models.DateTimeField(auto_now_add=True)
    blog_title = models.CharField(max_length=255, unique=True)
    description = RichTextUploadingField(
        blank=True, null=True, config_name='special')
    blog_image = models.ImageField(
        upload_to='blog_image', null=True, blank=True, help_text='Image Size 830 x 372')
    category = models.ForeignKey(
        BlogCategories, on_delete=models.CASCADE, related_name='blogs')
    tags = models.ManyToManyField(
        BlogTags, related_name='blog_tags', blank=True)
    slug = models.SlugField(
        max_length=255, unique=True, null=True, blank=True)

    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.blog_title

    def get_absolute_url(self):
        """
        Returns absolute url for a blog categories
        """
        return reverse("blog:blogdetail", kwargs={'blog_slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.blog_title)

        if self.blog_image:
            temp_image = Image.open(self.blog_image).convert('RGB')
            output_io_stream = BytesIO()
            temp_resized_image = temp_image.resize((830, 372))
            temp_resized_image.save(
                output_io_stream, format='JPEG', quality=60)
            output_io_stream.seek(0)
            self.blog_image = InMemoryUploadedFile(output_io_stream,
                                                   'ImageField', "%s.jpg" % self.blog_image.name.split('.')[0], 'image/jpeg', sys.getsizeof(output_io_stream), None)
        super(Blog, self).save(*args, **kwargs)


class BlogComments(models.Model):
    """
    Blog Comments Model
    """ 
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    comment = models.TextField()
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='blogs_comment')


    class Meta:
        app_label = 'blog'

    def __str__(self):
        return self.name

blog/forms.py
"""
Forms
"""
from django import forms

from blog.models import BlogComments


class BlogCommentsForm(forms.ModelForm):
    """
    BlogComments Form
    """
    class Meta:
        model = BlogComments
        fields = ['name', 'email', 'comment']

    def __init__(self, *args, **kwargs):
        super(BlogCommentsForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'placeholder' : 'Name', 'tabindex': "1", }
        self.fields['email'].widget.attrs = {
            'placeholder' : 'Email', 'tabindex': "2", }
        self.fields['comment'].widget.attrs = {
            'placeholder': 'Comment Here', 'tabindex': "3", }

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from app.common import CommonMixin
from .models import BlogCategories, Blog, BlogComments, BlogTags
from .forms import BlogCommentsForm
# Create your views here.


class BlogListView(CommonMixin, ListView):
    """
    Blog List View
    """
    model = Blog
    context_object_name = 'blog_list'
    template_name = 'blog_list.html'
    paginate_by = 4

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)

        context['blog_categories'] = BlogCategories.objects.all().order_by('title')
        context['latest_blogs'] = Blog.objects.all().order_by('id')[:3]
        context['blog_tags'] = BlogTags.objects.all().order_by('id')
        
        return context


@cache_page(60 * 15)
def blog_details_view(request, blog_slug):
    """
    Blog Details View
    """
    blog_details = Blog.objects.filter(slug=blog_slug).first()

    blog_categories = BlogCategories.objects.all().order_by('title')

    comment_list = BlogComments.objects.filter(
        blog=blog_details).order_by('-id')[:10]

    tag_list = BlogTags.objects.all().order_by('-id')

    recent_blogs = Blog.objects.all().order_by('-id')[:3]

    related_blogs = Blog.objects.filter(category=blog_details.category).exclude(
        id=blog_details.id)[:3]

    recent_comments = BlogComments.objects.all().order_by('-id')[:3]

    if request.method == "POST":
        comment_form = BlogCommentsForm(request.POST or None)
        if comment_form.is_valid():
            name = request.POST.get('name')
            email = request.POST.get('email')
            comment = request.POST.get('comment')
            answer = BlogComments.objects.create(
                name=name, email=email, comment=comment, blog=blog_details)
            answer.save()
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    else:
        comment_form = BlogCommentsForm()

    context = {

        'blog_details': blog_details,
        'comment_list': comment_list,
        'blog_categories': blog_categories,
        'form': comment_form,
        'tag_list': tag_list,
        'related_blogs' : related_blogs,
        'recent_blogs': recent_blogs,
        'recent_comments': recent_comments
    }
    return CommonMixin.render(request, 'blog_details.html', context)


@cache_page(60 * 15)
def blog_categories_details(request, blog_category_slug):
    """
    Blog Category detail view
    """
    category_details = BlogCategories.objects.filter(
        slug=blog_category_slug).first()

    blogs = Blog.objects.filter(category=category_details).order_by('-id')

    page = request.GET.get('page', 1)

    paginator = Paginator(blogs, 4)
    try:
        blog_list = paginator.page(page)
    except PageNotAnInteger:
        blog_list = paginator.page(1)
    except EmptyPage:
        blog_list = paginator.page(paginator.num_pages)

    blog_categories = BlogCategories.objects.all().exclude(
        id=category_details.id).order_by('title')

    latest_blogs = Blog.objects.all().order_by('id')[:3]

    blog_tags = BlogTags.objects.all().order_by('id')

    context = {
        'category_details': category_details,
        'blog_list': blog_list,
        'blog_categories': blog_categories,
        'latest_blogs': latest_blogs,
        'blog_tags': blog_tags
    }
    return CommonMixin.render(request, 'blog_category_details.html', context)


@cache_page(60 * 15)
def blog_tag_details(request, blog_tag_slug):
    """
    Blog Tag Detail View
    """
    blog_tag_details = BlogTags.objects.filter(slug=blog_tag_slug).first()

    blog_list = blog_tag_details.blog_tags.all()

    page = request.GET.get('page', 1)

    paginator = Paginator(blog_list, 4)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    blog_categories = BlogCategories.objects.all().order_by('title')
    latest_blogs = Blog.objects.all().order_by('id')[:3]
    blog_tags = BlogTags.objects.all().exclude(
        id=blog_tag_details.id).order_by('id')

    context = {

        'blog_tag_details': blog_tag_details,
        'blog_list': blogs,
        'blog_categories': blog_categories,
        'latest_blogs': latest_blogs,
        'blog_tags': blog_tags
    }
    return CommonMixin.render(request, 'blog_tag_details.html', context)


def search(request):
    """
    Search View
    """
    template = 'search_blog_list.html'

    query = request.GET.get('q')

    if query:
        result = Blog.objects.filter(Q(blog_title__icontains=query) | Q(
            description__icontains=query) | Q(category__title__icontains=query))
    else:
        result = Blog.objects.none()

    page = request.GET.get('page', 1)

    paginator = Paginator(result, 4)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    blog_categories = BlogCategories.objects.all().order_by('title')
    latest_blogs = Blog.objects.all().order_by('id')[:3]
    blog_tags = BlogTags.objects.all().order_by('id')

    context = {
        'search_result': query,
        'blog_list': blogs,
        'blog_categories': blog_categories,
        'latest_blogs': latest_blogs,
        'blog_tags': blog_tags
    }

    return CommonMixin.render(request, template, context)

blog/templates/blog_category_details.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} {{ category_details.title }} {% endblock %}

{% block content %}

<div class="breadcrumb-area">
    <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-3 pt-100 pb-95" style="background-image:url({% static 'assets/img/bg/breadcrumb-bg-3.jpg' %});">
        <div class="container">
            <h2>{{ category_details.title }}</h2>
        </div>
    </div>
    <div class="breadcrumb-bottom">
        <div class="container">
            <ul>
                <li><a href="{% url 'index' %}">Home</a> <span><i class="fa fa-angle-double-right"></i><a href="{% url 'blog:blog_list' %}">Blog List</a></span> <span><i class="fa fa-angle-double-right"></i>{{ category_details.title }}</span></li>
            </ul>
        </div>
    </div>
</div>
<div class="event-area pt-130 pb-130">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 col-lg-8">
                <div class="blog-all-wrap mr-40">
                    <div class="row">
                    {% for item in blog_list %}
                        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="single-blog mb-30">
                                <div class="blog-img">
                                    <a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">
	                                    {% if item.blog_image %}
	                                    	{% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone'  %}
	                                    		{% thumbnail item.blog_image "260x200" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% else %}
	                                    		{% thumbnail item.blog_image "260x200" format="WEBP" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% endif %}
	                                    {% else %}
	                                    	<img src="{% static 'assets/img/blog/blog-5.jpg' %}" alt="{{ item.blog_title }}">
	                                    {% endif %}
                                    </a>
                                </div>
                                <div class="blog-content-wrap">
                                    <span>{{ item.category.title }}</span>
                                    <div class="blog-content">
                                        <h4><a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">{{ item.blog_title }}</a></h4>
                                        {{ item.description|safe|truncatewords:"10" }}
                                        <div class="blog-meta">
                                            <ul>
                                                <li><a href="#"><i class="fa fa-comments-o"></i> {{ item.blogs_comment.count }}</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="blog-date">
                                        <a href="#"><i class="fa fa-calendar-o"></i> {{ item.date|date }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>

                    {% if is_paginated %}
                    <div class="pro-pagination-style text-center mt-25">
                        <ul>
                        {% if page_obj.has_previous %}
                            <li><a class="prev" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a></li>
                        {% endif %}

                        {% for i in paginator.page_range %}
                        	{% if page_obj.number == i %}
                            	<li><a class="active" href="#">{{ i }}</a></li>
                            {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                            	<li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li><a class="next" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-double-right"></i></a></li>
                        {% endif %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-xl-3 col-lg-4">
                <div class="sidebar-style">
                    <div class="sidebar-search mb-40">
                        <div class="sidebar-title mb-40">
                            <h4>Search</h4>
                        </div>
                        <form method="GET" action="{% url 'blog:search_blog' %}">

                            <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search">
                            <button type="submit"><i class="fa fa-search"></i></button>

                        </form>
                    </div>
                    <div class="sidebar-recent-post mb-35">
                        <div class="sidebar-title mb-40">
                            <h4>Recent Post</h4>
                        </div>
                        <div class="recent-post-wrap">
                        {% for item in latest_blogs %}
                            <div class="single-recent-post">
                                <div class="recent-post-img">
                                    <a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">
                                    	{% if item.blog_image %}
	                                    	{% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
	                                    		{% thumbnail item.blog_image "260x200" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% else %}
	                                    		{% thumbnail item.blog_image "260x200" format="WEBP" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% endif %}
	                                    {% else %}
	                                    	<img src="{% static 'assets/img/blog/blog-5.jpg' %}" alt="{{ item.blog_title }}">
	                                    {% endif %}
                                    </a>
                                </div>
                                <div class="recent-post-content">
                                    <h5><a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">{{ item.blog_title }}</a></h5>
                                    <span>{{ item.category.title }}</span>
                                    {{ item.description|safe|truncatewords:"8" }}
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </div>

                    <div class="sidebar-category mb-40">
                        <div class="sidebar-title mb-40">
                            <h4>Blog Categories</h4>
                        </div>
                        <div class="category-list">
                            <ul>
                            {% for item in blog_categories %}
                                <li><a href="{% url 'blog:blog_category_details' blog_category_slug=item.slug %}">{{ item.title }} <span>{{ item.blogs.count }}</span></a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="sidebar-tag-wrap">
                        <div class="sidebar-title mb-40">
                            <h4>Tag</h4>
                        </div>
                        <div class="sidebar-tag">
                            <ul>
                            {% for item in blog_tags %}
                                <li><a href="{% url 'blog:blog_tag_details' blog_tag_slug=item.slug %}">{{ item.name }}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog_tag_details.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} {{ blog_tag_details.name }} {% endblock %}

{% block content %}

<div class="breadcrumb-area">
    <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-3 pt-100 pb-95" style="background-image:url({% static 'assets/img/bg/breadcrumb-bg-3.jpg' %});">
        <div class="container">
            <h2>{{ blog_tag_details.name }}</h2>
        </div>
    </div>
    <div class="breadcrumb-bottom">
        <div class="container">
            <ul>
                <li><a href="{% url 'index' %}">Home</a> <span><i class="fa fa-angle-double-right"></i><a href="{% url 'blog:blog_list' %}">Blog List</a></span> <span><i class="fa fa-angle-double-right"></i>{{ blog_tag_details.name }}</span></li>
            </ul>
        </div>
    </div>
</div>
<div class="event-area pt-130 pb-130">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 col-lg-8">
                <div class="blog-all-wrap mr-40">
                    <div class="row">
                    {% for item in blog_list %}
                        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-12">
                            <div class="single-blog mb-30">
                                <div class="blog-img">
                                    <a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">
	                                    {% if item.blog_image %}
	                                    	{% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone'  %}
	                                    		{% thumbnail item.blog_image "260x200" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% else %}
	                                    		{% thumbnail item.blog_image "260x200" format="WEBP" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% endif %}
	                                    {% else %}
	                                    	<img src="{% static 'assets/img/blog/blog-5.jpg' %}" alt="{{ item.blog_title }}">
	                                    {% endif %}
                                    </a>
                                </div>
                                <div class="blog-content-wrap">
                                    <span>{{ item.category.title }}</span>
                                    <div class="blog-content">
                                        <h4><a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">{{ item.blog_title }}</a></h4>
                                        {{ item.description|safe|truncatewords:"10" }}
                                        <div class="blog-meta">
                                            <ul>
                                                <li><a href="#"><i class="fa fa-comments-o"></i> {{ item.blogs_comment.count }}</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="blog-date">
                                        <a href="#"><i class="fa fa-calendar-o"></i> {{ item.date|date }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>

                    {% if is_paginated %}
                    <div class="pro-pagination-style text-center mt-25">
                        <ul>
                        {% if page_obj.has_previous %}
                            <li><a class="prev" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a></li>
                        {% endif %}

                        {% for i in paginator.page_range %}
                        	{% if page_obj.number == i %}
                            	<li><a class="active" href="#">{{ i }}</a></li>
                            {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                            	<li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li><a class="next" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-double-right"></i></a></li>
                        {% endif %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-xl-3 col-lg-4">
                <div class="sidebar-style">
                    <div class="sidebar-search mb-40">
                        <div class="sidebar-title mb-40">
                            <h4>Search</h4>
                        </div>
                        <form method="GET" action="{% url 'blog:search_blog' %}">

                            <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search">
                            <button type="submit"><i class="fa fa-search"></i></button>

                        </form>
                    </div>
                    <div class="sidebar-recent-post mb-35">
                        <div class="sidebar-title mb-40">
                            <h4>Recent Post</h4>
                        </div>
                        <div class="recent-post-wrap">
                        {% for item in latest_blogs %}
                            <div class="single-recent-post">
                                <div class="recent-post-img">
                                    <a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">
                                    	{% if item.blog_image %}
	                                    	{% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
	                                    		{% thumbnail item.blog_image "260x200" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% else %}
	                                    		{% thumbnail item.blog_image "260x200" format="WEBP" as im %}
	                                    		<img src="{{ im.url }}" alt="{{ item.blog_title }}">
	                                    		{% endthumbnail %}
	                                    	{% endif %}
	                                    {% else %}
	                                    	<img src="{% static 'assets/img/blog/blog-5.jpg' %}" alt="{{ item.blog_title }}">
	                                    {% endif %}
                                    </a>
                                </div>
                                <div class="recent-post-content">
                                    <h5><a href="{% url 'blog:blogdetail' blog_slug=item.slug %}">{{ item.blog_title }}</a></h5>
                                    <span>{{ item.category.title }}</span>
                                    {{ item.description|safe|truncatewords:"8" }}
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </div>

                    <div class="sidebar-category mb-40">
                        <div class="sidebar-title mb-40">
                            <h4>Blog Categories</h4>
                        </div>
                        <div class="category-list">
                            <ul>
                            {% for item in blog_categories %}
                                <li><a href="{% url 'blog:blog_category_details' blog_category_slug=item.slug %}">{{ item.title }} <span>{{ item.blogs.count }}</span></a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="sidebar-tag-wrap">
                        <div class="sidebar-title mb-40">
                            <h4>Tag</h4>
                        </div>
                        <div class="sidebar-tag">
                            <ul>
                            {% for item in blog_tags %}
                                <li><a href="{% url 'blog:blog_tag_details' blog_tag_slug=item.slug %}">{{ item.name }}</a></li>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}