FAQ/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'FAQ'

urlpatterns = [
	url(r'^$', cache_page(60*15)(views.FaqListView.as_view()), name='faq_list'),
]

technology/urls.py
"""
Technology (URLs)
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'technology'

urlpatterns = [
	
	url(r'^$', cache_page(60*15)(views.TechnologyListView.as_view()), name='technology_list'),

	url(r'^(?P<technology_slug>[\w-]+)/details/$',
        cache_page(60*15)(views.TechnologyDetailView.as_view()), name='technology-details'),

	url(r'^enquiry/(?P<technology_slug>[\w-]+)/$',
        cache_page(60*15)(views.TechnologyQueryCreateView.as_view()), name='technical_enquiry'),

]

technology/models.py
from PIL import Image
import sys
import os
from io import BytesIO
from django.db import models
from django.core.validators import URLValidator, RegexValidator
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.files.uploadedfile import InMemoryUploadedFile
from embed_video.fields import EmbedVideoField

# Create your models here.

class TechnologyElements(models.Model):
	"""
	Technology Element Changes
	"""
	sample = models.CharField(max_length=100)
	heading = models.TextField()
	text = RichTextUploadingField(
		blank=True, null=True, config_name='special')
	quote = models.TextField(blank=True, null=True)
	image = models.ImageField(
		upload_to='service_image_common', null=True, blank=True, help_text='Image Size 830 x 372')
	about_us_image = models.ImageField(
		upload_to='about_image_service', null=True, blank=True, help_text='Image Size 268 x 99')

	class Meta:
		app_label = 'technology'

	def __str__(self):
		return self.sample

	def save(self, *args, **kwargs):

		if self.image:
			temp_image = Image.open(self.image).convert('RGB')
			output_io_stream = BytesIO()
			temp_resized_image = temp_image.resize((830, 372))
			temp_resized_image.save(
			    output_io_stream, format='JPEG', quality=60)
			output_io_stream.seek(0)
			self.image = InMemoryUploadedFile(output_io_stream,
			                                       'ImageField', "%s.jpg" % self.image.name.split('.')[0], 'image/jpeg', sys.getsizeof(output_io_stream), None)

		if self.about_us_image:
			temp_image = Image.open(self.about_us_image).convert('RGB')
			output_io_stream = BytesIO()
			temp_resized_image = temp_image.resize((268, 99))
			temp_resized_image.save(
			    output_io_stream, format='JPEG', quality=60)
			output_io_stream.seek(0)
			self.about_us_image = InMemoryUploadedFile(output_io_stream,
			                                       'ImageField', "%s.jpg" % self.about_us_image.name.split('.')[0], 'image/jpeg', sys.getsizeof(output_io_stream), None)

		super(TechnologyElements, self).save(*args, **kwargs)

class Technology(models.Model):
	"""
	Technology Model
	"""
	name = models.CharField(max_length=200)
	short_description = RichTextUploadingField(
		blank=True, null=True, config_name='special')
	detailed_description = RichTextUploadingField(
		blank=True, null=True, config_name='special')
	image = models.ImageField(
		upload_to='technology_image', null=True, blank=True, help_text='Image Size 1030 x 527')
	slug = models.SlugField(
        max_length=200, unique=True, null=True, blank=True)

	class Meta:
		app_label = 'technology'

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):

		self.slug = slugify(self.name)

		if self.image:
			temp_image = Image.open(self.image).convert('RGB')
			output_io_stream = BytesIO()
			temp_resized_image = temp_image.resize((1030, 527))
			temp_resized_image.save(
			    output_io_stream, format='JPEG', quality=60)
			output_io_stream.seek(0)
			self.image = InMemoryUploadedFile(output_io_stream,
			                                       'ImageField', "%s.jpg" % self.image.name.split('.')[0], 'image/jpeg', sys.getsizeof(output_io_stream), None)

		super(Technology, self).save(*args, **kwargs)


class TechnologyTabs(models.Model):
	"""
	Technology Tabs
	"""
	technology = models.ForeignKey(
        Technology, on_delete=models.CASCADE, related_name='technology_tabs', null=True)
	name = models.CharField(max_length=200)
	text = RichTextUploadingField(
		blank=True, null=True, config_name='special')
	slug = models.SlugField(
        max_length=200, unique=True, null=True, blank=True)

	class Meta:
		app_label = 'technology'

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):

		self.slug = slugify(self.name)

		super(TechnologyTabs, self).save(*args, **kwargs)


class TechnologyEnquiry(models.Model):
	"""
	Technology Enquiry Model
	"""
	technology = models.ForeignKey(
        Technology, on_delete=models.CASCADE, related_name='technologies')
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=100)
	phone_regex = RegexValidator(
		regex=r'^\+?1?\d{6,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
	# validators should be a list
	phone_no = models.CharField(
		validators=[phone_regex], max_length=17, null=True)
	subject = models.CharField(max_length=200)
	message = models.TextField()

	class Meta:
		app_label = 'technology'

	def __str__(self):
		return self.name

technology/forms.py
"""
Forms
"""
from django import forms

from .models import TechnologyEnquiry


class TechnologyEnquiryForm(forms.ModelForm):
    """
    TechnologyEnquiry Form
    """
    class Meta:
        model = TechnologyEnquiry
        fields = ['name', 'email', 'phone_no', 'subject', 'message', ]

    def __init__(self, *args, **kwargs):
        super(TechnologyEnquiryForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'name': 'name', 'placeholder': 'Full Name*', }
        self.fields['email'].widget.attrs = {
            'name': 'email', 'placeholder': 'Enter email*', }
        self.fields['phone_no'].widget.attrs = {
            'name': 'phone', 'placeholder': 'Phone Number*', }
        self.fields['subject'].widget.attrs = {
            'name': 'subject', 'placeholder': 'Subject*', }
        self.fields['message'].widget.attrs = {
            'name': 'message', 'placeholder': 'Write message*', }

technology/views.py
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from django.urls import reverse
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.views.generic import ListView, DetailView, CreateView

from about_us.models import AboutUs
from app.common import CommonMixin
from app.models import ConsultancyAndTechnologyFeedback
from contact_us.models import Contact_BackGround

from .forms import TechnologyEnquiryForm 
from .models import Technology, TechnologyElements, TechnologyTabs, TechnologyEnquiry
# Create your views here.


def send_tech_query_message_query_mail(contact):
    """
    Send Service Contact Mail
    """
    subject = contact.subject

    plaintext = get_template('query_from_tech/query.txt')

    htmly     = get_template('query_from_tech/query.html')

    context = { 'contact' : contact }

    from_email = settings.DEFAULT_FROM_EMAIL

    text_content = plaintext.render(context)
    html_content = htmly.render(context)

    msg = EmailMultiAlternatives(subject, text_content, from_email, ['learning@ankrglobal.com'])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


class TechnologyListView(CommonMixin, ListView):
	"""
	Technology List View
	"""
	model = Technology
	context_object_name = 'technology_list'
	template_name = 'technology_list.html'
	paginate_by = 12

	def get_queryset(self):
		return self.model.objects.all().order_by('-id')

	def get_context_data(self, **kwargs):
		context = super(TechnologyListView, self).get_context_data(**kwargs)

		context['review_list'] = ConsultancyAndTechnologyFeedback.objects.all().order_by('id')

		context['technology_elements'] = TechnologyElements.objects.filter(sample__exact='TECHNOLOGY-ELEMENTS').first()

		context['about'] = AboutUs.objects.filter(sample__exact='About-Us').first()

		return context


class TechnologyDetailView(CommonMixin, DetailView):
	"""
	Technology Details View
	"""
	context_object_name = 'technology_details'
	model = Technology
	template_name = 'technology_details.html'

	def get_object(self):
		technology_details = Technology.objects.filter(slug=self.kwargs['technology_slug']).first()
		return technology_details

	def get_context_data(self, **kwargs):
		context = super(TechnologyDetailView, self).get_context_data(**kwargs)

		context['technology_list'] = Technology.objects.all().order_by('id')

		context['tab_list'] = TechnologyTabs.objects.filter(technology=self.get_object()).order_by('id')

		return context


class TechnologyQueryCreateView(CommonMixin, CreateView):
	"""
	ContactUsQuery Create View
	"""
	form_class = TechnologyEnquiryForm
	template_name = "technology_enquiry.html"

	def get_success_url(self, **kwargs):
		technology_details = Technology.objects.filter(slug=self.kwargs['technology_slug']).first()
		technical_enquiry = TechnologyEnquiry.objects.filter(id=self.object.id).first()
		# send_tech_query_message_query_mail(contact=technical_enquiry)
		messages.success(
	    	self.request, 'Send successfully! Our Team will get in touch with you.')
		return reverse('technology:technical_enquiry', kwargs={'technology_slug': technology_details.slug})

	def form_valid(self, form):
		technology_details = Technology.objects.filter(slug=self.kwargs['technology_slug']).first()
		form.instance.technology = technology_details
		return super(TechnologyQueryCreateView, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(TechnologyQueryCreateView, self).get_context_data(**kwargs)

		context['technology_details'] = Technology.objects.filter(slug=self.kwargs['technology_slug']).first()

		context['contact_background'] = Contact_BackGround.objects.filter(
            sample__exact='Contact-Background').first()

		return context

technology/templates/technology_details.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block title %} {{ technology_details.name }} {% endblock %}

{% block content %}

<div class="breadcrumb-area">
    <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-3 pt-100 pb-95" style="background-image:url({% static 'assets/img/bg/breadcrumb-bg-3.jpg' %});">
        <div class="container">
            <h2>{{ technology_details.name }}</h2>
        </div>
    </div>
    <div class="breadcrumb-bottom">
        <div class="container">
            <ul>
                <li><a href="{% url 'index' %}">Home</a> <span><i class="fa fa-angle-double-right"></i><a href="{% url 'technology:technology_list' %}">Technology</a></span> <span><i class="fa fa-angle-double-right"></i>{{ technology_details.name }}</span></li>
            </ul>
        </div>
    </div>
</div>
<div class="event-area pt-130 pb-130">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="blog-details-wrap mr-40">
                    <div class="blog-details-top">
                    {% if technology_details.image %}
                        {% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone'  %}
                            {% thumbnail technology_details.image "1000x550" as im %}
                            <img src="{{ im.url }}" alt="{{ technology_details.name }}">
                            {% endthumbnail %}
                        {% else %}
                            {% thumbnail technology_details.image "1000x550" format="WEBP" as im %}
                            <img src="{{ im.url }}" alt="{{ technology_details.name }}">
                            {% endthumbnail %}
                        {% endif %}
                    {% else %}
                        <img src="{% static 'assets/img/blog/blog-details.jpg' %}" alt="{{ technology_details.name }}">
                    {% endif %}
                        <div class="blog-details-content-wrap">
                            

                            {{ technology_details.detailed_description|safe }}


                        </div>

                        <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-8">
                                <div class="course-tab-list nav pt-10 pb-10 mb-35">
                                {% for item in tab_list %}
                                    <a {% if forloop.first %}class="active"{% endif %} href="#{{ item.slug }}" data-toggle="tab" >
                                        <h4>{{ item.name }}</h4>
                                    </a>
                                {% endfor %}
                                </div>
                                <div class="tab-content jump">
                                {% for item in tab_list %}
                                    <div class="tab-pane active" id="{{ item.slug }}">
                                        <div class="over-view-content">
                                            {{ item.text|safe }}
                                            
                                        </div>
                                    </div>
                                {% endfor %}

                                </div>
                            </div>

                            <div class="col-xl-4 col-lg-4">
                                <div class="sidebar-category mb-40">
                                    <div class="sidebar-title mb-40">
                                        <h4>Technology</h4>
                                    </div>
                                    <div class="category-list">
                                        <ul>
                                            {% for item in technology_list %}
                                                <li><a href="{% url 'technology:technology-details' technology_slug=item.slug %}">{{ item.name }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                        <div class="text-center">
                            <a href="{% url 'technology:technical_enquiry' technology_slug=technology_details.slug %}" class="btn btn-success">Enquire Now</a>
                        </div>
                        <br>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

technology/templates/technology_enquiry.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} Enquiry {% endblock %}

{% block content %}


<div class="breadcrumb-area">
    <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-5 pt-100 pb-95" 
    	{% if contact_background.image %}
    		{% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
    			{% thumbnail contact_background.image "1900x330" as im %}
    			style="background-image:url('{{ im.url }}');"
    			{% endthumbnail %}
    		{% else %}
    			{% thumbnail contact_background.image "1900x330" format="WEBP" as im %}
    			style="background-image:url('{{ im.url }}');"
    			{% endthumbnail %}
    		{% endif %}
    	{% else %}
    		style="background-image:url({% static 'assets/img/bg/breadcrumb-bg-3.jpg' %});"
    	{% endif %}
    			>
        <div class="container">
            <h2>Enquiry For {{ technology_details.name }}</h2>
        </div>
    </div>
    <div class="breadcrumb-bottom">
        <div class="container">
            <ul>
                <li><a href="{% url 'index' %}">Home</a> <span><i class="fa fa-angle-double-right"></i>Enquiry For {{ technology_details.name }}</span></li>
            </ul>
        </div>
    </div>
</div>
<div class="contact-area pt-130 pb-130">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2">
                <!-- <div class="contact-map mr-70">
                    <div id="map"></div>
                </div> -->
            </div>

            <div class="col-lg-8">
                <div class="contact-form">
                    <div class="contact-title mb-45">
                        <h2>Enquiry For <span>{{ technology_details.name }}</span></h2>
                    </div>
                    <form method="POST">
                    	{% csrf_token %}

                    	
                        {{ form.name }}
                         {{ form.name.errors }}

                        {{ form.email }}
                         {{ form.email.errors }}

                         {{ form.phone_no }}
                          {{ form.phone_no.errors }}

                        {{ form.subject }}
                         {{ form.subject.errors }}

                        {{ form.message }}
                                    {{ form.message.errors }}
                        <button class="submit btn-style" type="submit">SEND MESSAGE</button>
                    </form>
                </div>
            </div>

            <div class="col-lg-2">
                <!-- <div class="contact-map mr-70">
                    <div id="map"></div>
                </div> -->
            </div>
        </div>
    </div>
</div>
<div class="contact-info-area bg-img pt-180 pb-140 default-overlay" 
        {% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
            style="background-image:url({% static 'assets/img/bg/contact-info.jpg' %});"
        {% else %}
            style="background-image:url({% static 'assets/img/bg/contact-info.webp' %});"
        {% endif %}
        >
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-12">
                <div class="single-contact-info mb-30 text-center">
                    <div class="contact-info-icon">
                        <span><i class="fa fa-calendar-o"></i></span>
                    </div>
                    <p>{{ common_info.address|safe|striptags }}</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="single-contact-info mb-30 text-center">
                    <div class="contact-info-icon">
                        <span><i class="fa fa-calendar-o"></i></span>
                    </div>
                    <div class="contact-info-phn">
                        <div class="info-phn-title">
                            <span>Phone : </span>
                        </div>
                        <div class="info-phn-number">
                            <p>{{ common_info.phone_no }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-12">
                <div class="single-contact-info mb-30 text-center">
                    <div class="contact-info-icon">
                        <span><i class="fa fa-calendar-o"></i></span>
                    </div>
                    <a href="mailto:{{ common_info.email }}">{{ common_info.email }}</a>
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<br>
<div class="brand-logo-area pb-130">
    <div class="container">
    <div class="section-title mb-75">
            <h2>Our <span>Students</span></h2>
            <p>Working in leading Companies </p>
        </div>
        {% if not client_list %}
            <div class="brand-logo-active owl-carousel">
                <div class="single-brand-logo">
                    <a href="#"><img src="{% static 'assets/img/brand-logo/1.png' %}" alt=""></a>
                </div>
                <div class="single-brand-logo">
                    <a href="#"><img src="{% static 'assets/img/brand-logo/2.png' %}" alt=""></a>
                </div>
                <div class="single-brand-logo">
                    <a href="#"><img src="{% static 'assets/img/brand-logo/3.png' %}" alt=""></a>
                </div>
                <div class="single-brand-logo">
                    <a href="#"><img src="{% static 'assets/img/brand-logo/4.png' %}" alt=""></a>
                </div>
                <div class="single-brand-logo">
                    <a href="#"><img src="{% static 'assets/img/brand-logo/5.png' %}" alt=""></a>
                </div>
                <div class="single-brand-logo">
                    <a href="#"><img src="{% static 'assets/img/brand-logo/6.png' %}" alt=""></a>
                </div>
                <div class="single-brand-logo">
                    <a href="#"><img src="{% static 'assets/img/brand-logo/2.png' %}" alt=""></a>
                </div>
            </div>
        {% else %}
            <div class="brand-logo-active owl-carousel">
                {% for item in client_list %}
                <div class="single-brand-logo">
                    <a href="#">
                    {% if item.logo_image %}
                        {% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone'  %}
                            {% thumbnail item.logo_image "78x84" as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                            {% endthumbnail %}
                        {% else %}
                            {% thumbnail item.logo_image "78x84" format="WEBP" as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                            {% endthumbnail %}
                        {% endif %}
                    {% else %}
                        <img src="{% static 'assets/img/brand-logo/1.png' %}" alt="{{ item.name }}">
                    {% endif %}
                    </a>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}