FAQ/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'FAQ'

urlpatterns = [
	url(r'^$', cache_page(60*15)(views.FaqListView.as_view()), name='faq_list'),
]

courses/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'courses'

urlpatterns = [

	url(r'^(?P<course_slug>[\w-]+)/$',
        views.course_details_view, name='course_details'),

    url(r'^category/(?P<category_slug>[\w-]+)/$',
        views.course_category_details_view, name='course_category_details'),

    url(r'^sub-category/(?P<sub_category_slug>[\w-]+)/$',
        views.course_sub_category_details_view, name='course_sub_category_details'),

    url(r'^all-courses/list/$',
        views.all_course_list, name='all_course_list'),

    url(r'^my-courses/list/$',
        views.my_course_list_view, name='my_course_list'),

    url(r'^my-courses/details/(?P<course_slug>[\w-]+)/$',
        views.my_course_details, name='my_course_details'),

    url(r'^courses/details/(?P<course_slug>[\w-]+)/admin/$',
        views.admin_course_details, name='admin_course_details'),

    url(r'^my-courses/content/details/(?P<course_content_pk>\d+)/$',
        views.my_course_content_details, name='my_course_content'),

    url(r'^download-zip-file/(?P<course_pk>\d+)/$',
        views.download_zip_files, name='download_zip_files'),

    url(r'^user-course-list/(?P<profile_pk>\d+)/$',
        views.user_courses_list, name='user_courses_list'),

    url(r'^user/course/(?P<course_pk>\d+)/update/user/(?P<profile_pk>\d+)/$',
        views.course_update_ajax, name='course_update'),

    url(r'^certificate/(?P<course_slug>[\w-]+)/$',
        views.course_completion_certificate, name='course_certificate'),

    url(r'^quiz/courses/$',
        views.course_for_quiz_list_view, name='quiz_course_list'),

    url(r'^(?P<course_slug>[\w-]+)/question/order_no/(?P<question_order>\d+)/$',
        views.create_user_quiz, name='create_user_quiz'),

    url(r'^(?P<course_slug>[\w-]+)/quiz/result/$',
        views.quiz_result_view, name='quiz_result'),

    url(r'^(?P<course_slug>[\w-]+)/quiz/restart/$',
        views.restart_quiz, name='restart_quiz'),


    url(r'^(?P<course_slug>[\w-]+)/quiz/answers/$',
        views.all_users_answer, name='quiz_answers'),

    url(r'^package/list/$',
        cache_page(60*15)(views.PackageListView.as_view()), name='package_list'),

    url(r'^package/details/(?P<package_slug>[\w-]+)/$',
        cache_page(60*15)(views.PackageDetailView.as_view()), name='package_details'),

    url(r'^search/result/$',
        views.search_courses, name='search_courses'),

    url(r'^search/result/admin/$',
        views.search_admin_courses, name='search_admin_courses'),

    url(r'^search/result/student/$',
        views.search_student_courses, name='search_student_courses'),

    url(r'^skills/list/$',
        views.skills_list, name='skills_list'),

    url(r'^add-subscription/courses/(?P<profile_pk>\d+)/$',
        views.user_course_manual_subscription_list, name='user_course_manual_subscription_list'),

    url(r'^add-course/manually/(?P<course_pk>\d+)/user/(?P<profile_pk>\d+)/$',
        views.add_course_to_student, name='add_course_to_student'),

    url(r'^unlock/certificate/(?P<user_courses_pk>\d+)/$',
        views.unlock_certificate, name='unlock_certificate'),

]

ecommerce_cart/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

app_name = 'ecommerce_cart'

urlpatterns = [
	url(r'^$', views.cart_item_list, name='cart_view'),
	
	url(r'^add-to-cart/(?P<course_id>[-\w]+)/$',
        views.add_to_cart, name="add_to_cart"),

	url(r'^add-package-to-cart/(?P<package_id>[-\w]+)/$',
        views.add_package_to_cart, name="add_package_to_cart"),

	url(r'^item/delete/(?P<item_id>[-\w]+)/$',
        views.delete_from_cart, name='delete_item'),

	url(r'^items/clear/$',
		views.clear_cart, name='clear_items'),

	url(r'^coupon/(?P<coupon_pk>\d+)/clear/$',
        views.remove_coupon, name='clear_coupon'),

	url(r'^checkout/$',
        views.check_out, name='check_out'),

	url(r'^create/order/$',
        views.place_order_view, name='place_order'),

	url(r'^create/free/order/payment/$',
        views.finish_submit_view, name='finish_submit_view'),

	url(r'^order/confirmed/(?P<user_order_slug>[-\w]+)/$',
        views.thanks_page, name='thanks'),

	url(r'^your/order/$',
        views.user_order_list, name='user_order_list'),

	url(r'^order/details/(?P<user_order_slug>[-\w]+)/$',
        views.order_details, name='order_details'),

	url(r'^coupon/list/$',
        views.CouponListView.as_view(), name='coupon_list'),

	url(r'^coupon/search/$',
        views.coupon_search_autocomplete_ajax, name='coupon_search'),

	url(r'^coupon/create/$',
        views.CouponCreateView.as_view(), name='coupon_create'),

	url(r'^coupon/(?P<coupon_pk>\d+)/update/$',
        views.CouponUpdateView.as_view(), name='coupon_update'),

	url(r'^coupon/(?P<coupon_pk>\d+)/delete/$',
        views.delete_coupon, name='coupon_delete'),

	url(r'^coupon/(?P<coupon_pk>\d+)/details/$',
        views.coupon_details_view, name='coupon_details'),

	url(r'^coupon/order/(?P<order_pk>\d+)/details/$',
        views.item_in_cart_while_coupons, name='item_in_cart_while_coupons'),

]

courses/forms.py
"""
Forms
"""
from django import forms

from .models import CourseReview, CourseQuestion, UserCourses, Questions, Answer, UserQuiz

class DateInput(forms.DateInput):
    """
    Widgets support for date input
    """
    input_type = 'date'


class CourseReviewForm(forms.ModelForm):
    """
    CourseReview Form
    """

    def __init__(self, *args, **kwargs):
        super(CourseReviewForm, self).__init__(*args, **kwargs)
        self.fields['review'].widget.attrs = {'class': 'form-control', }

    class Meta:
        model = CourseReview
        fields = ('review',)


class CourseQuestionForm(forms.ModelForm):
    """
    CourseQuestion Form
    """

    def __init__(self, *args, **kwargs):
        super(CourseQuestionForm, self).__init__(*args, **kwargs)
        self.fields['question'].widget.attrs = {'class': 'form-control', }

    class Meta:
        model = CourseQuestion
        fields = ('question',)

class UserCoursesForm(forms.ModelForm):
    """
    UserCourses Form
    """

    def __init__(self, *args, **kwargs):
        super(UserCoursesForm, self).__init__(*args, **kwargs)
        self.fields['date_of_expiry'].widget.attrs = {'class': 'form-control', }
    

    class Meta:
        model = UserCourses
        fields = ('date_of_expiry',)
        widgets = {
            'date_of_expiry': DateInput(),
        }


class UserQuizForm(forms.ModelForm):
    """
    User Quiz Form
    """ 
    class Meta:
        model = UserQuiz
        fields = ('answer',)

    def __init__(self, *args, **kwargs):
        self.question = kwargs.pop('question', None)

        super(UserQuizForm, self).__init__(*args, **kwargs)


        self.fields['answer'] = forms.ModelChoiceField(queryset=Answer.objects.filter(question=self.question), widget=forms.RadioSelect, empty_label=None)

courses/views.py
import zipfile
import os
from io import BytesIO
import decimal
import datetime
from datetime import date
from dateutil.relativedelta import relativedelta

from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Sum, Value, Count, Avg, Q
from django.db.models.functions import Coalesce
from django.urls import reverse
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages

from about_us.models import AboutUs
from app.common import CommonMixin, CommonAdminMixin
from app.models import CertificateSignatures, Notification, CourseFeedback
from ecommerce_cart.models import DemoItems, DemoPackageItems
from ecommerce_cart.extras import generate_certificate_no
from email_configurations.views import course_completion_mail, send_course_question_mail
from user_profile.models import Profile

from .forms import CourseReviewForm, CourseQuestionForm, UserCoursesForm, UserQuizForm
from .models import CourseCategory, CourseSubCategory, Courses, CourseContent, CourseFilesAttached, CourseReview, UserCourses, CourseContentViewedUser, CourseQuestion, Questions, Answer, UserQuiz, CoursesPackages, CourseElements, SkillsTrainingVideos
# Create your views here.

@cache_page(60 * 15)
def course_category_details_view(request, category_slug):
	"""
	Course Category Detail View
	"""
	course_category_details = CourseCategory.objects.filter(slug=category_slug).first()

	sub_category_list = CourseSubCategory.objects.filter(category=course_category_details).order_by('id')

	context = {
		'course_category_details' : course_category_details,
		'sub_category_list' : sub_category_list
	}
	return CommonMixin.render(request, 'course_category_details.html', context)


@cache_page(60 * 15)
def course_sub_category_details_view(request, sub_category_slug):
	"""
	Course Sub Category Detail View
	"""
	course_sub_category_details = CourseSubCategory.objects.filter(slug=sub_category_slug).first()

	courses = Courses.objects.filter(sub_category=course_sub_category_details, show_course=True).order_by('id')

	page = request.GET.get('page', 1)

	paginator = Paginator(courses, 9)
	try:
		course_list = paginator.page(page)
	except PageNotAnInteger:
		course_list = paginator.page(1)
	except EmptyPage:
		course_list = paginator.page(paginator.num_pages)

	package_list = CoursesPackages.objects.filter(sub_category=course_sub_category_details).order_by('id')

	context = {
		'course_sub_category_details' : course_sub_category_details,
		'course_list' : course_list,
		'package_list' : package_list
	}
	return CommonMixin.render(request, 'course_sub_category_details.html', context)


@cache_page(60 * 15)
def course_details_view(request, course_slug):
	"""
	Course Details View
	"""
	category_list = CourseCategory.objects.all().order_by('name')

	course_details = Courses.objects.filter(slug=course_slug).first()

	course_content = CourseContent.objects.filter(course=course_details).order_by('id')

	related_courses = Courses.objects.filter(sub_category=course_details.sub_category, show_course=True).exclude(id=course_details.id).order_by('id')[:5]

	course_reviews = CourseReview.objects.filter(course=course_details).order_by('id')

	if request.user.is_authenticated:
		applied_course = UserCourses.objects.filter(user=request.user, course=course_details).first()

		cart_course = DemoItems.objects.filter(user=request.user, course=course_details).first()
	else:
		applied_course = None

		cart_course = None

	review_avg = CourseReview.objects.filter(course=course_details).aggregate(the_avg=Coalesce(Avg('rating'), Value(0)))['the_avg']

	review_list = CourseFeedback.objects.all().order_by('id')

	video_list = SkillsTrainingVideos.objects.all().order_by('id')

	context = {
		'category_list' : category_list,
		'course_details' : course_details,
		'course_content' : course_content,
		'related_courses' : related_courses,
		'course_reviews' : course_reviews,
		'applied_course' : applied_course,
		'cart_course' : cart_course,
		'review_avg' : review_avg,
		'review_list' : review_list,
		'video_list' : video_list
	}
	return CommonMixin.render(request, 'course_details.html', context)

@login_required
@cache_page(60 * 15)
def all_course_list(request):
	"""
	All Course List
	"""
	if not request.user.is_superuser:
		messages.error(request, 'You have no permission to access the requested resource!')
		return redirect(reverse('index_student'))


	courses = Courses.objects.all().order_by('id')

	page = request.GET.get('page', 1)

	paginator = Paginator(courses, 9)
	try:
		course_list = paginator.page(page)
	except PageNotAnInteger:
		course_list = paginator.page(1)
	except EmptyPage:
		course_list = paginator.page(paginator.num_pages)

	context = {
		'course_list' : course_list
	}
	return CommonAdminMixin.render(request, 'all_course.html', context)


@cache_page(60 * 15)
def skills_list(request):
	"""
	Skills List View
	"""
	category_list = CourseCategory.objects.all().order_by('name')

	course_elements = CourseElements.objects.filter(sample__exact='COURSE-ELEMENTS').first()

	review_list = CourseFeedback.objects.all().order_by('id')

	video_list = SkillsTrainingVideos.objects.all().order_by('id')

	about = AboutUs.objects.filter(sample__exact='About-Us').first()

	context = {
		'about' : about,
		'category_list' : category_list,
		'course_elements' : course_elements,
		'review_list' : review_list,
		'video_list' : video_list
	}
	return CommonMixin.render(request, 'skills.html', context)

@login_required
def my_course_list_view(request):
	"""
	My Course List
	"""
	courses = UserCourses.objects.filter(user=request.user).order_by('id')

	page = request.GET.get('page', 1)

	paginator = Paginator(courses, 9)
	try:
		course_list = paginator.page(page)
	except PageNotAnInteger:
		course_list = paginator.page(1)
	except EmptyPage:
		course_list = paginator.page(paginator.num_pages)

	if request.user.is_authenticated:
		#### Courses Removal on expiry

		# Iterate through them
		for item in courses:
			if item.date_of_expiry < timezone.now():

				# If the expiration date is bigger than first remove user from course user list
				item.course.subscribed_users.remove(item.user)
				item.course.save()

				# Then Delete the User Course Model
				item.delete()

	context = {
		'course_list' : course_list
	}
	return CommonAdminMixin.render(request, 'my_course.html', context)

@login_required
@cache_page(60 * 15)
def admin_course_details(request, course_slug):
	"""
	My Course Details
	"""
	if not request.user.is_superuser:
		messages.error(request, 'You have no permission to access the requested resource!')
		return redirect(reverse('index_student'))


	course_details = Courses.objects.filter(slug=course_slug).first()

	course_content = CourseContent.objects.filter(course=course_details).order_by('id')

	course_content_completed = CourseContentViewedUser.objects.filter(user=request.user,course=course_details, completed=True).order_by('id')

	course_content_total = course_content.aggregate(
            the_sum=Coalesce(Count('id'), Value(0)))['the_sum'] # Total Course Content

	course_content_completed_total = course_content_completed.aggregate(
            the_sum=Coalesce(Count('id'), Value(0)))['the_sum'] # Total Course Content Completed

	if course_content:
		percentage_completed = (course_content_completed_total / course_content_total) * 100
	else:
		percentage_completed = 0

	applied_course = UserCourses.objects.filter(user=request.user, course=course_details).first()

	review_avg = CourseReview.objects.filter(course=course_details).aggregate(the_avg=Coalesce(Avg('rating'), Value(0)))['the_avg']

	if review_avg:

		rating_avg = range(int(review_avg))
		empty_avg_star = range(int(5)-int(review_avg))

	else:

		rating_avg = range(int(0))
		empty_avg_star = range(int(5)-int(0))

			

	context = {
		'course_details' : course_details,
		'course_content' : course_content,
		'applied_course' : applied_course,
		'percentage_completed' : percentage_completed,
		'rating_avg' : rating_avg,
		'empty_avg_star' : empty_avg_star,
		'review_avg' : review_avg
	}
	return CommonAdminMixin.render(request, 'admin_course_details.html', context)

@login_required
def my_course_details(request, course_slug):
	"""
	My Course Details
	"""
	course_details = Courses.objects.filter(slug=course_slug).first()

	course_content = CourseContent.objects.filter(course=course_details).order_by('id')

	course_content_completed = CourseContentViewedUser.objects.filter(user=request.user,course=course_details, completed=True).order_by('id')

	course_content_total = course_content.aggregate(
            the_sum=Coalesce(Count('id'), Value(0)))['the_sum'] # Total Course Content

	course_content_completed_total = course_content_completed.aggregate(
            the_sum=Coalesce(Count('id'), Value(0)))['the_sum'] # Total Course Content Completed

	if course_content:
		percentage_completed = (course_content_completed_total / course_content_total) * 100
	else:
		percentage_completed = 0

	applied_course = UserCourses.objects.filter(user=request.user, course=course_details).first()

	if request.method == 'POST' and 'btnform1' in request.POST:
		review_form = CourseReviewForm(request.POST or None)
		if review_form.is_valid():
			rating = request.POST.get('rating')
			review = request.POST.get('review')
			review = CourseReview.objects.create(user=request.user, review=review, rating=rating, course=course_details)
			review.save()
			messages.success(
                        request, 'Your Review is submitted successfully')
			return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
	else:
		review_form = CourseReviewForm()

courses/templates/course_category_details.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} {{ course_category_details.name }} {% endblock %}

{% block content %}

<div class="breadcrumb-area">
    <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-3 pt-100 pb-95" style="background-image:url({% static 'assets/img/bg/breadcrumb-bg-3.jpg' %});">
        <div class="container">
            <h2>{{ course_category_details.name }}</h2>
        </div>
    </div>
    <div class="breadcrumb-bottom">
        <div class="container">
            <ul>
                <li><a href="{% url 'index' %}">Home</a> <span><i class="fa fa-angle-double-right"></i>{{ course_category_details.name }}</span></li>
            </ul>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
{% for item in sub_category_list %}
    {% if item.course_sub_category.all %}
        <div class="course-area bg-img">
            <div class="container">
                <div class="section-title mb-75 course-mrg-small">
                    <h2> <span>{{ item.name }}</span></h2>
                    {{ item.sub_heading_text|safe }}
                </div>
                <div class="course-slider-active-5">
                    {% for obj in item.course_sub_category.all %}
                    {% if obj.show_course == True %}
                    <div class="single-course" style="margin-right: 20px;margin-bottom: 80px;">
                        <div class="course-img">
                            <a href="{% url 'courses:course_details' course_slug=obj.slug %}">
                            {% if obj.image %}
                                {% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
                                    {% thumbnail obj.image "290x270" as im %}
                                    <img class="animated" src="{{ im.url }}" alt="{{ obj.name }}">
                                    {% endthumbnail %}
                                {% else %}
                                    {% thumbnail obj.image "290x270" format="WEBP" as im %}
                                    <img class="animated" src="{{ im.url }}" alt="{{ obj.name }}">
                                    {% endthumbnail %}
                                {% endif %}
                            {% else %}
                                <img class="animated" src="{% static 'assets/img/course/course-1.jpg' %}" alt="{{ obj.name }}">
                            {% endif %}
                            </a>
                            {% if obj.action_text %}
                                <span>{{ obj.action_text }}</span>{% endif %}
                        </div>
                        <div class="course-content">
                            <h4><a href="{% url 'courses:course_details' course_slug=obj.slug %}">{{ obj.name }}</a></h4>
                            {{ obj.description|safe }}
                        </div>
                        <div class="course-position-content">
                            <div class="credit-duration-wrap">
                                <div class="sin-credit-duration">
                                    <i class="fa fa-inr"></i>
                                    <span>Price : INR <del>{{ obj.course_price }}</del></span>
                                </div>
                                <div class="sin-credit-duration">
                                    <i class="fa fa-inr"></i>
                                    <span>Discounted Price : {{ obj.course_total }}</span>
                                </div>
                                
                            </div>
                            <div class="credit-duration-wrap">
                                
                                <div class="sin-credit-duration">
                                    <i class="fa fa-clock-o"></i>
                                    <span>Duration : {{ obj.duration }}</span>
                                </div>

                                <div class="sin-credit-duration">
                                    <i class="fa fa-clock-o"></i>
                                    <span>Mode : {{ obj.mode_of_delivery }}</span>
                                </div>
                            </div>
                            <div class="course-btn">
                                {% if user in obj.subscribed_users.all %}
                                    <a class="applied-btn" href="#">Already Applied</a>
                                {% elif obj.course_in_demo.all and user.user_demo_items.all %}
                                    <a class="cart-btn" href="{% url 'ecommerce_cart:cart_view' %}">GO TO CART</a>
                                {% else %}
                                    <a class="default-btn" href="{% url 'ecommerce_cart:add_to_cart' course_id=obj.id %}">ADD TO CART</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}

                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}



{% endblock %}

courses/templates/course_update.html
{% load crispy_forms_tags %}
<form method="post" data-url="{% url 'courses:course_update' course_pk=form.instance.id profile_pk=profile_details.pk %}" class="update-form">
	{% csrf_token %}
		<div class="modal-header">
		<h5 class="modal-title" >Change Expiry Date</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
		</div>
		<div class="modal-body">
		{{ form|crispy }}
		</div>
		<div class="modal-footer">
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		<button type="submit" id="reload_answer_update" class="btn btn-primary">Update</button>
		</div>
</form>


<script type="text/javascript">
$('#reload_answer_update').click(function() {
    location.reload();
});
</script>

courses/templates/package_list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} All Packages {% endblock %}

{% block content %}

<div class="breadcrumb-area">
    <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-3 pt-100 pb-95" style="background-image:url({% static 'assets/img/bg/breadcrumb-bg-3.jpg' %});">
        <div class="container">
            <h2>All Packages</h2>
            
        </div>
    </div>
    <div class="breadcrumb-bottom">
        <div class="container">
            <ul>
                <li><a href="{% url 'index' %}">Home</a> <span><i class="fa fa-angle-double-right"></i>All Packages</span></li>
            </ul>
        </div>
    </div>
</div>

<div class="event-area pt-130 pb-130">
    <div class="container">
        <div class="row">
        {% for item in course_package_list %}
            <div class="col-lg-4 col-md-6">
                <div class="single-event mb-55 event-gray-bg">
                    <div class="event-img">
                        <a href="{% url 'courses:package_details' package_slug=item.slug %}">
                        {% if item.image %}
                        	{% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
                        		{% thumbnail item.image "370x227" as im %}
                        		<img src="{{ im.url }}" alt="{{ item.name }}">
                        		{% endthumbnail %}
                        	{% else %}
                        		{% thumbnail item.image "370x227" format="WEBP" as im %}
                        		<img src="{{ im.url }}" alt="{{ item.name }}">
                        		{% endthumbnail %}
                        	{% endif %}
                        {% else %}
                        	<img src="{% static 'assets/img/event/event-5.jpg' %}" alt="{{ item.name }}">
                        {% endif %}
                        </a>
                        <div class="event-date-wrap">
                            <span class="event-date">{{ item.courses.count }}</span>
                            <span>Course{{ item.courses.count|pluralize }}</span>
                        </div>
                    </div>
                    <div class="event-content">
                        <h3><a href="{% url 'courses:package_details' package_slug=item.slug %}">{{ item.package_name|truncatewords:"5" }}</a></h3>
                        {{ item.description|safe|truncatewords:"12" }}
                        <div class="event-meta-wrap">
                            <div class="event-meta">
                                <i class="fa fa-inr"></i>
                                <span>INR {{ item.package_total }}</span>
                            </div>
                            <!-- <div class="event-meta">
                                <i class="fa fa-clock-o"></i>
                                <span>{{ item.duration }}</span>
                            </div> -->
                        </div>
                    </div>
                    <div class="course-btn">
                        {% if user in item.subscribed_users.all %}
                            <a class="applied-btn" href="#">Already Applied</a>
                        {% elif item.package_in_demo.all and user.user_demo_items_packages.all %}
                        <a class="cart-btn" href="{% url 'ecommerce_cart:cart_view' %}">GO TO CART</a>
                        {% else %}
                            <a class="default-btn" href="{% url 'ecommerce_cart:add_package_to_cart' package_id=item.id %}">ADD TO CART</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        {% if is_paginated %}
            <div class="pro-pagination-style text-center mt-25">
                <ul>
                {% if page_obj.has_previous %}
                    <li><a class="prev" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a></li>
                {% endif %}

                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li><a class="active" href="#">{{ i }}</a></li>
                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li><a class="next" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-double-right"></i></a></li>
                {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

courses/templates/user_course_list_ajax.html
{% load static %}
{% load thumbnail %}
{% load l10n %}
{% load mathfilters %}
{% load poll_extras %}



                {% for item in user_courses %}
                <tr>

                    <td>

                        <div class="media align-items-center">
                            <div class="avatar avatar-xs mr-2">
                            {% if item.course.image %}
                                {% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
                                    {% thumbnail item.course.image "128x128" as im %}
                                    <img src="{{ im.url }}" alt="Avatar" class="avatar-img rounded-circle">
                                    {% endthumbnail %}
                                {% else %}
                                    {% thumbnail item.course.image "128x128" format="WEBP" as im %}
                                    <img src="{{ im.url }}" alt="Avatar" class="avatar-img rounded-circle">
                                    {% endthumbnail %}
                                {% endif %}
                            {% else %}
                                <img src="{% static 'educasta/assets/images/256_luke-porter-261779-unsplash.jpg' %}" alt="Avatar" class="avatar-img rounded-circle">
                            {% endif %}
                            </div>
                            <div class="media-body">

                                <span class="js-lists-values-employee-name">{{ item.course.name }}</span>

                            </div>
                        </div>

                    </td>

                    <td>
                        <div class="media align-items-center">
                            {{ item.date_of_subscription|date }}
                            
                        </div>
                    </td>

                    <td>{{ item.date_of_expiry|date }}</td>
                    <td>{{ item.subscription_type }}</td>
                    <td>&#8377;  {{ item.total }}</td>
                    <td><button class="show-form-update btn btn-warning btn-xs" data-url="{% url 'courses:course_update' course_pk=item.id profile_pk=profile_details.pk %}">Change</button></td>
                    <td>{% if item.is_certificate_unlocked != True %}<a class="btn btn-info btn-xs" href ="{% url 'courses:unlock_certificate' user_courses_pk=item.id %}">Unlock</a>{% else %}<a class="btn btn-success btn-xs" href ="#">Unlocked Already</a>{% endif %}</td>
                </tr>
                {% endfor %}