FAQ/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'FAQ'

urlpatterns = [
	url(r'^$', cache_page(60*15)(views.FaqListView.as_view()), name='faq_list'),
]

courses/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

from django.views.decorators.cache import cache_page

app_name = 'courses'

urlpatterns = [

	url(r'^(?P<course_slug>[\w-]+)/$',
        views.course_details_view, name='course_details'),

    url(r'^category/(?P<category_slug>[\w-]+)/$',
        views.course_category_details_view, name='course_category_details'),

    url(r'^sub-category/(?P<sub_category_slug>[\w-]+)/$',
        views.course_sub_category_details_view, name='course_sub_category_details'),

    url(r'^all-courses/list/$',
        views.all_course_list, name='all_course_list'),

    url(r'^my-courses/list/$',
        views.my_course_list_view, name='my_course_list'),

    url(r'^my-courses/details/(?P<course_slug>[\w-]+)/$',
        views.my_course_details, name='my_course_details'),

    url(r'^courses/details/(?P<course_slug>[\w-]+)/admin/$',
        views.admin_course_details, name='admin_course_details'),

    url(r'^my-courses/content/details/(?P<course_content_pk>\d+)/$',
        views.my_course_content_details, name='my_course_content'),

    url(r'^download-zip-file/(?P<course_pk>\d+)/$',
        views.download_zip_files, name='download_zip_files'),

    url(r'^user-course-list/(?P<profile_pk>\d+)/$',
        views.user_courses_list, name='user_courses_list'),

    url(r'^user/course/(?P<course_pk>\d+)/update/user/(?P<profile_pk>\d+)/$',
        views.course_update_ajax, name='course_update'),

    url(r'^certificate/(?P<course_slug>[\w-]+)/$',
        views.course_completion_certificate, name='course_certificate'),

    url(r'^quiz/courses/$',
        views.course_for_quiz_list_view, name='quiz_course_list'),

    url(r'^(?P<course_slug>[\w-]+)/question/order_no/(?P<question_order>\d+)/$',
        views.create_user_quiz, name='create_user_quiz'),

    url(r'^(?P<course_slug>[\w-]+)/quiz/result/$',
        views.quiz_result_view, name='quiz_result'),

    url(r'^(?P<course_slug>[\w-]+)/quiz/restart/$',
        views.restart_quiz, name='restart_quiz'),


    url(r'^(?P<course_slug>[\w-]+)/quiz/answers/$',
        views.all_users_answer, name='quiz_answers'),

    url(r'^package/list/$',
        cache_page(60*15)(views.PackageListView.as_view()), name='package_list'),

    url(r'^package/details/(?P<package_slug>[\w-]+)/$',
        cache_page(60*15)(views.PackageDetailView.as_view()), name='package_details'),

    url(r'^search/result/$',
        views.search_courses, name='search_courses'),

    url(r'^search/result/admin/$',
        views.search_admin_courses, name='search_admin_courses'),

    url(r'^search/result/student/$',
        views.search_student_courses, name='search_student_courses'),

    url(r'^skills/list/$',
        views.skills_list, name='skills_list'),

    url(r'^add-subscription/courses/(?P<profile_pk>\d+)/$',
        views.user_course_manual_subscription_list, name='user_course_manual_subscription_list'),

    url(r'^add-course/manually/(?P<course_pk>\d+)/user/(?P<profile_pk>\d+)/$',
        views.add_course_to_student, name='add_course_to_student'),

    url(r'^unlock/certificate/(?P<user_courses_pk>\d+)/$',
        views.unlock_certificate, name='unlock_certificate'),

]

ecommerce_cart/urls.py
"""
Urls
"""
from django.conf.urls import url
from . import views

app_name = 'ecommerce_cart'

urlpatterns = [
	url(r'^$', views.cart_item_list, name='cart_view'),
	
	url(r'^add-to-cart/(?P<course_id>[-\w]+)/$',
        views.add_to_cart, name="add_to_cart"),

	url(r'^add-package-to-cart/(?P<package_id>[-\w]+)/$',
        views.add_package_to_cart, name="add_package_to_cart"),

	url(r'^item/delete/(?P<item_id>[-\w]+)/$',
        views.delete_from_cart, name='delete_item'),

	url(r'^items/clear/$',
		views.clear_cart, name='clear_items'),

	url(r'^coupon/(?P<coupon_pk>\d+)/clear/$',
        views.remove_coupon, name='clear_coupon'),

	url(r'^checkout/$',
        views.check_out, name='check_out'),

	url(r'^create/order/$',
        views.place_order_view, name='place_order'),

	url(r'^create/free/order/payment/$',
        views.finish_submit_view, name='finish_submit_view'),

	url(r'^order/confirmed/(?P<user_order_slug>[-\w]+)/$',
        views.thanks_page, name='thanks'),

	url(r'^your/order/$',
        views.user_order_list, name='user_order_list'),

	url(r'^order/details/(?P<user_order_slug>[-\w]+)/$',
        views.order_details, name='order_details'),

	url(r'^coupon/list/$',
        views.CouponListView.as_view(), name='coupon_list'),

	url(r'^coupon/search/$',
        views.coupon_search_autocomplete_ajax, name='coupon_search'),

	url(r'^coupon/create/$',
        views.CouponCreateView.as_view(), name='coupon_create'),

	url(r'^coupon/(?P<coupon_pk>\d+)/update/$',
        views.CouponUpdateView.as_view(), name='coupon_update'),

	url(r'^coupon/(?P<coupon_pk>\d+)/delete/$',
        views.delete_coupon, name='coupon_delete'),

	url(r'^coupon/(?P<coupon_pk>\d+)/details/$',
        views.coupon_details_view, name='coupon_details'),

	url(r'^coupon/order/(?P<order_pk>\d+)/details/$',
        views.item_in_cart_while_coupons, name='item_in_cart_while_coupons'),

]

ecommerce_cart/forms.py
"""
Forms
"""
from django import forms
from django.conf import settings

from courses.models import Courses, CoursesPackages

from .models import Coupon

from django.contrib.admin.widgets import FilteredSelectMultiple



class DateInput(forms.DateInput):
    """
    Widgets support for date input
    """
    input_type = 'date'


class CouponForm(forms.ModelForm):
	"""
	Coupon Form
	"""

	def __init__(self, *args, **kwargs):
		super(CouponForm, self).__init__(*args, **kwargs)

		for field in self.fields.values():
			field.widget.attrs = {"class": "form-control"}

		self.fields['coupon_type'].widget.attrs = {
			'class': 'select2_demo_1 form-control','onchange': 'coupon_type_change(this)', }

		self.fields['discount_type'].widget.attrs = {
			'class': 'select2_demo_4 form-control','onchange': 'discount_type_change(this)', }

		self.fields['courses'].widget.attrs = {
			'class': 'select2_demo_3 form-control','multiple' : 'multiple', }

		self.fields['packages'].widget.attrs = {
			'class': 'select2_demo_2 form-control','multiple' : 'multiple', }


	class Meta:
		model = Coupon
		widgets = {
			'valid_till': DateInput(),
		}
		fields = ['coupon_code', 'coupon_type','discount_type','valid_till','discount_percentage','discount_amount','courses','packages',]

ecommerce_cart/views.py
import decimal
import datetime
from datetime import date
from dateutil.relativedelta import relativedelta

from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.db.models import Q
from django.views.generic import ListView, CreateView, UpdateView
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Value, Count
from django.db.models.functions import Coalesce
from django.http import HttpResponseRedirect
from django.db import transaction

from app.common import CommonMixin, CommonAdminMixin

from .razorpay import RAZORPAY_KEY, new_razorpay_order, fetch_razorpay_order_info, verify_razorpay_signature
from .etran_validation import subscribe_course

from courses.models import Courses, UserCourses, CoursesPackages
from .extras import generate_order_id
from .forms import CouponForm
from .models import CartItems, DemoItems, DemoPackageItems, Coupon, UserAppliedCoupon, UserOrders, UserCouponUsage
# Create your views here.

@login_required
def cart_item_list(request):
    """
    Cart View
    """
    existing_orders = CartItems.objects.filter(
        user=request.user, is_ordered=False)  # Getting Items in Cart

    user_applied_coupon = UserAppliedCoupon.objects.filter(user=request.user).first()


    cart_total = existing_orders.aggregate(
        the_sum=Coalesce(Sum('cart_total'), Value(0)))['the_sum']  # Cart Sub Total Calculation

    grand_total = cart_total

    discount = 0

    if user_applied_coupon: 
        if user_applied_coupon.coupon.coupon_type == 'ON SUBTOTAL': # For Altogether Discount on Final Cart Amount
            if user_applied_coupon.coupon.discount_type == 'ON PERCENTAGE':
                discount = (cart_total * user_applied_coupon.coupon.discount_percentage) / 100
                grand_total = cart_total - discount
            else:
                discount = user_applied_coupon.coupon.discount_amount
                grand_total = cart_total - user_applied_coupon.coupon.discount_amount



    query = request.GET.get('q')

    result = None

    if query:
        result = Coupon.objects.filter(coupon_code__exact=query)
        if not result:
            messages.error(request, 'Discount Coupon Is Invalid')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    elif query == "":
        result = None
        messages.error(request, 'Coupon code is Blank')
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    else:
        result = None

    if result:
        for r in result:
            usage_count = UserCouponUsage.objects.filter(user=request.user, coupon=r).first()
            if datetime.datetime.now().date() > r.valid_till:
                messages.error(request, 'Discount Coupon No Longer Exist')
            elif usage_count:
                messages.error(request, 'Discount Coupon Already Used By You on ' + str(usage_count.date_used.date()))
            else:
                user_coupon = UserAppliedCoupon.objects.create(
                        user=request.user, coupon=r)
                user_coupon.save() 
                coupon_usage = UserCouponUsage.objects.create(
                        user=request.user, coupon=r)
                coupon_usage.save()
                for item in existing_orders:
                    item.save()
                messages.success(
                        request, 'Discount Coupon Applied Successfully')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


    context = {
    	'existing_orders' : existing_orders,
    	'cart_total' : cart_total,
        'coupon_discount': round(discount, 2),
        'grand_total' : round(grand_total,2),
        'user_applied_coupon' : user_applied_coupon 
    }
    return CommonMixin.render(request, 'cart.html', context)


@login_required
def add_to_cart(request, **kwargs):
    """
    Add To Cart View
    """

    existing_orders = CartItems.objects.filter(
        user=request.user, is_ordered=False)

    course = Courses.objects.filter(id=kwargs.get('course_id', "")).first()

    if existing_orders:
        for item in existing_orders:
            if item.packages:
                for obj in item.packages.courses.all():
                    if obj.id == course.id:
                        messages.error(request, 'This course is already under '+ item.packages.package_name +' package added to cart earlier')
                        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    add_item = CartItems.objects.create(
        course=course, user=request.user, ref_code=generate_order_id(), is_ordered=False)

    add_item.save()

    add_demo = DemoItems.objects.create(user = request.user, course=course)

    add_demo.save()

    messages.success(
        request, 'Selected Product is successfully added to cart')

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
def delete_from_cart(request, item_id):
    """
    Delete One Item From Cart
    """

    item_to_delete = CartItems.objects.filter(pk=item_id).first()


    if item_to_delete.course:
        delete_demo = DemoItems.objects.filter(user = request.user, course=item_to_delete.course).first()

        delete_demo.delete()

    if item_to_delete.packages:
        delete_demo_package = DemoPackageItems.objects.filter(user = request.user, packages=item_to_delete.packages).first()
        delete_demo_package.delete()
    
    if item_to_delete:
        item_to_delete.delete()

    messages.success(
        request, 'Selected Product is successfully removed from cart')

    return redirect(reverse('ecommerce_cart:cart_view'))


@login_required
def add_package_to_cart(request, **kwargs):
    """
    Add To Cart View
    """
    existing_orders = CartItems.objects.filter(
        user=request.user, is_ordered=False)

    package = CoursesPackages.objects.filter(id=kwargs.get('package_id', "")).first()

    flag = 0
    if existing_orders:
        for item in existing_orders:
            for obj in package.courses.all():
                if obj.id == item.course.id: 
                    demo_items = DemoItems.objects.filter(user=request.user, course=obj)
                    for dem in demo_items:
                        dem.delete()
                    item.delete()
                    flag = 1
    

    add_item = CartItems.objects.create(
        packages=package, user=request.user, ref_code=generate_order_id(), is_ordered=False)

    add_item.save()

    add_demo = DemoPackageItems.objects.create(user=request.user, packages=package)

    add_demo.save()

    if flag == 1:
        messages.success(request, 'Looks Like one of the courses in your cart is already under this package we have adjusted it for you')
    else:
        messages.success(request, 'Selected Package is successfully added to cart')

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))



@login_required
def clear_cart(request):
    """
    Clear All Item From Cart View
    """
    item_to_delete = CartItems.objects.filter(
        user=request.user, is_ordered=False)

    for item in item_to_delete:
        item.delete()
    messages.success(
        request, 'Cart is cleared successfully')
    return redirect(reverse('ecommerce_cart:cart_view'))

@login_required
def remove_coupon(request, coupon_pk):
    """
    Remove Coupon View
    """
    coupon_details = Coupon.objects.filter(pk=coupon_pk).first()

    user_coupon = UserAppliedCoupon.objects.filter(
        user=request.user).first()

    user_coupon.delete()

    coupon_usage = UserCouponUsage.objects.filter(
                        user=request.user, coupon=coupon_details).first()

    coupon_usage.delete()

    existing_orders = CartItems.objects.filter(
        user=request.user, is_ordered=False)  # Getting Items in Cart

    for item in existing_orders:
        item.save()

    messages.success(
        request, 'Discount Coupon removed successfully')
    return redirect(reverse('ecommerce_cart:cart_view'))

@login_required
def check_out(request):
    """
    Check Out View
    """
    existing_orders = CartItems.objects.filter(
        user=request.user, is_ordered=False)  # Getting Items in Cart

    user_applied_coupon = UserAppliedCoupon.objects.filter(user=request.user).first()


    cart_total = existing_orders.aggregate(
        the_sum=Coalesce(Sum('cart_total'), Value(0)))['the_sum']  # Cart Sub Total Calculation

    grand_total = cart_total

    razorpay_order_amount = int(round(grand_total*decimal.Decimal(100.00), 0))

    discount = 0

    if user_applied_coupon: 
        if user_applied_coupon.coupon.coupon_type == 'ON SUBTOTAL': # For Altogether Discount on Final Cart Amount
            if user_applied_coupon.coupon.discount_type == 'ON PERCENTAGE':
                discount = (cart_total * user_applied_coupon.coupon.discount_percentage) / 100
                grand_total = cart_total - discount
                razorpay_order_amount = int(round(grand_total*decimal.Decimal(100.00), 0))
            else:
                discount = user_applied_coupon.coupon.discount_amount
                grand_total = cart_total - user_applied_coupon.coupon.discount_amount
                razorpay_order_amount = int(round(grand_total*decimal.Decimal(100.00), 0))



    if grand_total > 0:
        try:
            razorpay_order_info = new_razorpay_order(razorpay_order_amount, generate_order_id(), {})
            razorpay_order_id = razorpay_order_info.get('id')
        except Exception as ex:
            raise Http404("The server is experiencing issue with the payment gateway. Please try again later.")
    else:
        razorpay_order_id = None


    context = {
        'existing_orders' : existing_orders,
        'user_applied_coupon' : user_applied_coupon,

ecommerce_cart/templates/check_out.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} Check Out {% endblock %}

{% block content %}

<div class="breadcrumb-area">
    <div class="breadcrumb-top default-overlay bg-img breadcrumb-overly-3 pt-100 pb-95" style="background-image:url({% static 'assets/img/bg/breadcrumb-bg-3.jpg' %});">
        <div class="container">
            <h2>Cart</h2>
            <p>After you've reviewed the items in your Shopping Cart, you're ready to proceed to checkout and complete your order.</p>
        </div>
    </div>
    <div class="breadcrumb-bottom">
        <div class="container">
            <ul>
                <li><a href="{% url 'index' %}">Home</a> <span><i class="fa fa-angle-double-right"></i>CheckOut</span></li>
            </ul>
        </div>
    </div>
</div>

<div class="checkout-area pt-130 pb-130">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="table-content table-responsive cart-table-content">
                        <table>
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Course Name</th>
                                    <th>Valid Till</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for item in existing_orders %}
                                {% if item.course %}
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="{% url 'courses:course_details' course_slug=item.course.slug %}">
                                            {% if item.course.image %}
                                            	{% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
                                            		{% thumbnail item.course.image "82x82" as im %}
                                            		<img src="{{ im.url }}" alt="{{ item.course.name }}">
                                            		{% endthumbnail %}
                                            	{% else %}
                                            		{% thumbnail item.course.image "82x82" format="WEBP" as im %}
                                            		<img src="{{ im.url }}" alt="{{ item.course.name }}">
                                            		{% endthumbnail %}
                                            	{% endif %}
                                            {% else %}
                                            	<img src="{% static 'assets/img/cart/cart-1.png' %}" alt="{{ item.course.name }}">
                                            {% endif %}
                                            </a>
                                        </td>
                                        <td class="product-name"><a href="{% url 'courses:course_details' course_slug=item.course.slug %}">{{ item.course.name }}</a></td>
                                        <td class="product-subtotal">{{ item.course.course_valid_till_months }} Months</td>
                                        <td class="product-subtotal">&#8377; {{ item.cart_total }}
                                            {% if item.coupon_discount != 0 %}
                                                <span class="badge badge-success">(-) &#8377; {{ item.coupon_discount|floatformat:2 }}</span>
                                            {% endif %}
                                        </td>

                                    </tr>
                                {% else %}
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="{% url 'courses:package_details' package_slug=item.packages.slug %">
                                            {% if item.packages.image %}
                                                {% if request.user_agent.browser.family in browser_family or request.user_agent.device.family == 'iPhone' %}
                                                    {% thumbnail item.packages.image "82x82" as im %}
                                                    <img src="{{ im.url }}" alt="{{ item.packages.package_name }}">
                                                    {% endthumbnail %}
                                                {% else %}
                                                    {% thumbnail item.packages.image "82x82" format="WEBP" as im %}
                                                    <img src="{{ im.url }}" alt="{{ item.packages.package_name }}">
                                                    {% endthumbnail %}
                                                {% endif %}
                                            {% else %}
                                                <img src="{% static 'assets/img/cart/cart-1.png' %}" alt="{{ item.packages.package_name }}">
                                            {% endif %}
                                            </a>
                                        </td>
                                        <td class="product-name"><a href="{% url 'courses:package_details' package_slug=item.packages.slug %">{{ item.packages.package_name }}</a></td>
                                        <td class="product-subtotal">According to courses</td>
                                        <td class="product-subtotal">&#8377; {{ item.cart_total }}
                                            {% if item.coupon_discount != 0 %}
                                                <span class="badge badge-success">(-) &#8377; {{ item.coupon_discount|floatformat:2 }}</span>
                                            {% endif %}
                                        </td>

                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
            <div class="col-lg-5">
                <div class="your-order-area">
                    <h3>Your order</h3>
                    <div class="your-order-wrap gray-bg-4">
                        <div class="your-order-product-info">
                        	<div class="your-order-top">
                        		<ul>
                                    <li>Sub Total</li>
                                    <li> &#8377; {{ cart_total }}</li>
                                </ul>
                        	</div>
                        	{% if user_applied_coupon.coupon.coupon_type == 'ON SUBTOTAL' %}
                            <div class="your-order-bottom">
                                <ul>
                                    <li>Coupon Discount ({{ user_applied_coupon.coupon.discount_percentage }}%)</li>
                                    <li>(-) &#8377; {{ discount }}</li>
                                </ul>
                            </div>
                            {% endif %}
                            <div class="your-order-total">
                                <ul>
                                    <li class="order-total">Total</li>
                                    <li>&#8377; {{ grand_total }}</li>
                                </ul>
                            </div>
                        </div>
<!--                         <div class="payment-method">
                            <div class="payment-accordion element-mrg">
                                <div class="panel-group" id="accordion">
                                    <div class="panel payment-accordion">
                                        <div class="panel-heading" id="method-one">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordion" href="#method1">
                                                    Direct bank transfer
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="method1" class="panel-collapse collapse show">
                                            <div class="panel-body">
                                                <p>Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel payment-accordion">
                                        <div class="panel-heading" id="method-two">
                                            <h4 class="panel-title">
                                                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#method2">
                                                    Check payments
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="method2" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel payment-accordion">
                                        <div class="panel-heading" id="method-three">
                                            <h4 class="panel-title">
                                                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#method3">
                                                    Cash on delivery
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="method3" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Please send a check to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> -->
                    </div>
                    <div class="Place-order mt-25">
                    {% if grand_total > 0 %}
                        <form action="{% url 'ecommerce_cart:place_order' %}" method="POST">
                            <script 
                                src="https://checkout.razorpay.com/v1/checkout.js"
                                data-key="{{ RAZORPAY_KEY }}",
                                data-amount="{{ razorpay_order_amount }}"
                                data-currency="INR"
                                data-order_id="{{ razorpay_order_id }}"
                                data-buttontext="Make Payment"
                                data-name="ANKR LEARNING" ,
                                data-description="{{ order_description }}"
                                data-image="{% static 'logo_ankr_new.png' %}"
                                data-prefill.name="{{ user.profile.username }}"
                                data-prefill.email="{{ user.profile.email }}"
                                data-prefill.contact="{{ user.profile.phone_no }}"
                                data-theme.color="#263949">
                            </script>
                            {% csrf_token %}
                        </form>
                    {% elif grand_total == 0%}
                        <a class="btn-hover" href="{% url 'ecommerce_cart:finish_submit_view' %}">Make Payment</a>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ecommerce_cart/templates/coupon_ajax_list.html
{% if coupon_list %}

<div class="wrapper wrapper-content animated fadeInRight ecommerce" id="coupon_autocomplete">

<table class="table mb-0 thead-border-top-0">
    <thead>
        <tr>

            <th style="width: 37px;">Coupon Code</th>

            <th style="width: 37px;">Coupon Type</th>
            <th style="width: 37px;">Discount Type</th>
            <th style="width: 120px;">Discount Percentage/ Amount</th>
            <th style="width: 37px;">Valid Till</th>
            <th style="width: 37px;">View Details</th>
            <th style="width: 50px;">Update Coupon</th>
            <th style="width: 120px;">Delete Coupon</th>
        </tr>
    </thead>
    <tbody class="list" id="staff02">
        {% for item in coupon_list %}
        <tr>

            <td>

                <span class="js-lists-values-employee-name">{{ item.coupon_code }}</span>

            </td>

             <td>
                {{ item.coupon_type }}
            </td>


            <td>
                {{ item.discount_type }}
            </td>

            {% if item.discount_percentage %}
                <td><small class="text-muted">{{ item.discount_percentage }} %</small></td>
            {% else %}
                <td><small class="text-muted">&#8377; {{ item.discount_amount }} </small></td>
            {% endif %}

            <td>
                {{ item.valid_till|date }}
            </td>

            <td><a href="{% url 'ecommerce_cart:coupon_details' coupon_pk=item.pk %}" class="btn btn-success">View</a></td>

            <td><a href="{% url 'ecommerce_cart:coupon_update' coupon_pk=item.pk %}" class="btn btn-warning">Update</a></td>

            <td><a href="{% url 'ecommerce_cart:coupon_delete' coupon_pk=item.pk %}" onclick="return confirm('Are you sure you want to delete this coupon?');" class="btn btn-danger">Delete</a></td>
        </tr>
        {% endfor %}

    </tbody>
</table>

</div>
{% else %}

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-danger alert-dismissable" id="limit-alert">
              <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
              <strong>No Coupons Found</strong>
            </div>
        </div>
    </div>
</div>

{% endif %}